apiVersion: v1
kind: Service
metadata:
  name: muruchat
  labels:
    app: muruchat
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
      targetPort: 8080
      name: 30001-tcp
  selector:
    app: muruchat